### ISSUE TITLE
COMP230 Pre-production Tasks and Pitches - platform

### ISSUE THREAD

**Issue by NecroReindeer** [Falmouth-Games-Academy/bsc-assignment-briefs#11]
At the top of the assignment brief, it states:

> Use any programming language or technology.

However, in the marking rubric under the "Portability and Navigability" criterion, in the "Professional Proficiency" column it says

> Appropriate cross-platform compatibility on Linux, Windows, and MacOS.

What about the scenario where a student was developing a component/tool to be used for mobile games that was cross platform with Android and iOS? Or for a Universal Windows Platform App that's compatible with XBox One and Windows 10 (Mobile and Desktop)? 
In the latter scenario, one would have to use DirectX, which would mean it would not be possible to achieve compatibility with Linux and MacOS.

**Comment by Adrir** [comment]
We do not currently have access to all the necessary mobile platforms to conduct such an assessment. If there is demand for it, we can purchase some and revise the rubric accordingly.

**Comment by NecroReindeer** [comment]
Am I still able to develop for one of those platforms if I have access to them? I was interested in Xbox One/UWPA, which I do have access to.
Since it does state

> Use any programming language or technology.

and the only reference to specific platforms is in the "Professional Proficiency" grade of that particular criterion.

**Comment by Adrir** [comment]
So long as it can be tested on Windows, Linux, and/or MacOS, yes. UWPA are fine because we can run them on Windows.

**Comment by NecroReindeer** [comment]
Ok. 
In that situation, how would it fit into the previously mentioned criterion on the marking rubric?
Am I correct in assuming that this scenario is covered by the use of the word "Appropriate"? (i.e. in that scenario it's not 'appropriate' for it to be compatible with Linux/MacOS)

**Comment by Adrir** [comment]
"Appropriate" here does indeed offer flexibility, but refers to the relevant part(s) of the deliverable. Students will not receive credit for cross-platform compatibility if they choose to make a platform-specific product. However, the "product" may only be one part of a larger deliverable.

So, for example, if the product were a specific game component, the game component itself could be implemented as a cross-platform library, which may only have been integrated into a platform-specific game at the time it is delivered.

In another example, the product could be a game-making tool. In principle, the tool is cross-platform because it is built using standard types and has abstracted out the file system, GUI, etc. However, only a Windows-specific GUI is actually implemented because that was the only platform the stakeholders were actually using.

**Comment by Adrir** [comment]
In your case, you could make an Xbox One game, but product itself may be something different like a procedural level generator that could, at least in principle, be integrated into another student's Linux game. The Xbox One game itself serves as a means to demonstrate and market the product.

See, for example, [SpeedTree](http://www.speedtree.com/).
