### ISSUE TITLE
COMP230 Pre-production Tasks and Pitches - "Professionalism & Cohesion" criterion query

### ISSUE THREAD

**Issue by NecroReindeer** [Falmouth-Games-Academy/bsc-assignment-briefs#8]
Regarding the "Professionalism & Cohesion" criteria on COMP230's "Pre-production Tasks and Pitches" assignment:
Using the "Professional Proficiency" grade as an example, one of the requirements to achieve this is:

> The group has demonstrated extensive professionalism, functioning highly effectively in a team and/or customer engagement context.

What is expected of students who choose to work as an individual in regards to this?

**Comment by Adrir** [comment]
We will examine evidence of engagement with stakeholders and potential stakeholders where students choose to work as individuals.

**Comment by NecroReindeer** [comment]
Who are the stakeholders/potential stakeholders? And how would "engagement" be demonstrated and measured?

**Comment by Adrir** [comment]
Stakeholders will vary on a project by project basis. They could your investors, clients, and/or potential customers. It is up to students to identify and define who their stakeholders are.  Typically, they will either be Games Academy staff or BA/BSc students. However, stakeholders could be external so long as engagement can be evidenced. They can even be implied, if they are unreachable!

Engagement can be evidenced in a variety of ways. For example, discussion on issue pages on GitHub, discussion on Slack, discussion on appropriate web forums, and notes/minutes from a face-to-face meetings, and even market research.  These will usually be used to justify progress in sprint reviews as well as the existence and priority of user stories during sprint planning sessions. 

Please also note that, in cases the stakeholders are implied or otherwise unreachable, conducting research to develop suitable personas would qualify as 'engagement'.
